export const architectureLayers = [
  {n:'01',name:'AI Intelligence & Orchestration',purpose:'Understand, reason, coordinate and act.',problem:'Turns expanding technical capability into useful institutional decisions.',tech:'AI models · agents · research · simulation',examples:'AGONiQ · Patients Intelligence',partners:'AI platforms · cloud · research institutions'},
  {n:'02',name:'Data, Evidence & Observability',purpose:'Make activity measurable and accountable.',problem:'Creates the evidence required to evaluate systems and outcomes.',tech:'Telemetry · analytics · audit trails · evidence systems',examples:'AGONiQ · Patients Intelligence',partners:'Data infrastructure · universities · health systems'},
  {n:'03',name:'Institutional Governance',purpose:'Determine what is permitted, accountable and trusted.',problem:'Establishes oversight, controls and legitimacy.',tech:'Rules · permissions · appeals · human oversight',examples:'Patients Intelligence · AGONiQ',partners:'Standards bodies · institutions · policy experts'},
  {n:'04',name:'Identity & Reputation',purpose:'Establish who participated and what they demonstrated.',problem:'Makes verified achievement portable across institutions.',tech:'Digital identity · credentials · reputation',examples:'AGONiQ',partners:'Universities · employers · identity providers'},
  {n:'05',name:'Rights & Provenance',purpose:'Establish who created, owns, licenses or contributed.',problem:'Clarifies attribution and permissions in AI-enabled markets.',tech:'Rights registries · attestations · licensing',examples:'EsportsX · NBG asset registry research',partners:'Creators · IP platforms · licensing partners'},
  {n:'06',name:'Economic & Settlement Infrastructure',purpose:'Move value between participants.',problem:'Enables transparent, appropriate participation in new markets.',tech:'Payments · settlement · royalties · controls',examples:'Tubaron / Cabo Verde · EsportsX',partners:'Payment providers · sponsors · commerce platforms'},
  {n:'07',name:'Community & Participation',purpose:'Convert infrastructure into real ecosystems.',problem:'Connects systems to people, institutions and local context.',tech:'Education · media · community funding · marketplaces',examples:'Tubaron / Cabo Verde',partners:'Communities · educators · regional operators'},
];
export const ventures=[
  {name:'AGONiQ',stage:'Architecture in development',category:'Human–AI Performance Infrastructure',problem:'How do organizations measure and develop human–AI capability?',emphasis:'Intelligence · Trust · Identity · Credentials · Governance',need:'Universities · employers · AI platforms'},
  {name:'Patients Intelligence',stage:'Exploratory initiative',category:'Patient-Centered AI',problem:'How should patient-generated AI intelligence enter clinical systems responsibly?',emphasis:'Intelligence · Trust · Governance · Evidence · Human escalation',need:'Health systems · researchers · patient advocates'},
  {name:'Tubaron / Cabo Verde',stage:'Ecosystem concept',category:'Coordinated Regional Infrastructure',problem:'How can culture, sport, education, diaspora and opportunity connect through shared infrastructure?',emphasis:'Community · Economic participation · Ownership · Media · Governance',need:'Regional operators · diaspora leaders · institutions'},
  {name:'EsportsX',stage:'Portfolio development',category:'Esports IP & Licensing',problem:'How can esports IP, education, brands and operating assets be structured for scalable licensing?',emphasis:'Ownership · Rights · Licensing · Education · Media · Commerce',need:'Operators · educators · licensing partners'},
];
export const researchTracks=[
  ['01','Verifiable Human–AI Credentials','AGONiQ','Can competency records become independently verifiable and portable between universities, employers and institutions?'],
  ['02','Digital Asset & IP Registry','National Brand Group','Can NBG structure provenance and rights across domains, brands, research, media, curricula and software?'],
  ['03','Programmable Global Settlement','Portfolio-wide research','How can global partnerships, royalties, prize payments, sponsorships and grants settle more transparently?'],
  ['04','Transparent Community Funding','Tubaron / Cabo Verde','Can participants better understand how funding moves and what outcomes it produces?'],
  ['05','Creator & Producer Economics','Cross-portfolio research','Can provenance and programmable revenue-sharing improve creator participation?'],
];

export type Venture = {
  slug:string; name:string; stage:string; maturity:'Priority'|'Architecture extension'|'Portfolio development';
  category:string; question:string; description:string; components:string[]; focus:string; needs:string[];
  systems:string[];
};

export const portfolio:Venture[]=[
  {slug:'agoniq',name:'AGONiQ',stage:'Architecture in development',maturity:'Priority',category:'Human–AI Performance Infrastructure',question:'How do organizations measure and develop human–AI capability?',description:'AGONiQ is developing systems that make human–AI capability measurable, demonstrable and portable. Its architecture connects structured challenges with interaction evidence, scoring, verification, credentials and reputation.',components:['Intelligence','Trust','Identity','Credentials','Governance'],focus:'Advancing the architecture toward institutional pilots and partner validation.',needs:['Universities','Employers','AI platforms','Assessment specialists'],systems:['Structured challenges','Human–AI interaction evidence','Performance scoring','Credential architecture','Independent verification']},
  {slug:'patients-intelligence',name:'Patients Intelligence',stage:'Exploratory initiative',maturity:'Priority',category:'Patient-Centered AI',question:'How should patient-generated AI intelligence enter clinical systems responsibly?',description:'Patients Intelligence explores how AI-supported research and reasoning created by patients can enter healthcare systems responsibly—structured for review without replacing clinical judgment.',components:['Intelligence','Trust','Governance','Evidence','Human escalation'],focus:'Preparing bounded validation pathways with healthcare, research and patient stakeholders.',needs:['Health systems','Clinical researchers','Patient advocates','Governance experts'],systems:['Structured intake','Evidence packaging','Appropriate routing','Urgency signals','Human clinical oversight']},
  {slug:'tubaron-cabo-verde',name:'Tubaron / Cabo Verde',stage:'Ecosystem concept',maturity:'Priority',category:'Coordinated Regional Infrastructure',question:'How can culture, sport, education, diaspora and opportunity connect through shared infrastructure?',description:'Tubaron explores coordinated infrastructure connecting Cabo Verdean culture, sport, education, media, diaspora participation and economic opportunity.',components:['Community','Economic participation','Ownership','Media','Governance'],focus:'Structuring a rights-aware ecosystem model for partner review and phased implementation.',needs:['Regional operators','Diaspora leaders','Educators','Community institutions'],systems:['Research and intelligence','Cultural and sports media','Diaspora participation','Education pathways','Transparent community funding']},
  {slug:'esportsx',name:'EsportsX',stage:'Portfolio development',maturity:'Priority',category:'Esports IP & Institutional Development',question:'How can esports intellectual property, education, brands and operating assets be structured for licensing and participation?',description:'EsportsX organizes NBG’s experience, educational concepts, event formats, brands and digital assets across competitive gaming.',components:['Ownership','Rights','Licensing','Education','Media','Commerce'],focus:'Organizing intellectual property and digital assets into partner-ready licensing opportunities.',needs:['Operators','Educators','Rights holders','Licensing partners'],systems:['Strategic advisory','Competition architecture','Curriculum concepts','Media systems','Brand and domain licensing']},
  {slug:'warzai',name:'Warzai',stage:'Prototype concept',maturity:'Architecture extension',category:'Multimodal Human–AI Competition',question:'How can creative human–AI work be evaluated in structured, compelling formats?',description:'A proposed challenge format spanning written, visual and mixed-media work for professionals and students.',components:['Intelligence','Evidence','Scoring','Participation'],focus:'Developing pilot formats, evaluation criteria and production requirements.',needs:['Educators','Creative organizations','Assessment designers'],systems:['Challenge formats','Evidence capture','Judging protocols','Performance records']},
  {slug:'cerebran',name:'Cerebran',stage:'Research concept',maturity:'Architecture extension',category:'Enterprise Human–AI Capability',question:'How can teams demonstrate human–AI competency in workplace contexts?',description:'An enterprise and workforce-development concept for evaluating human–AI collaboration in organizational settings.',components:['Intelligence','Trust','Credentials','Workforce'],focus:'Defining enterprise use cases, assessment criteria and potential pilot partners.',needs:['Employers','Learning leaders','Workforce organizations'],systems:['Team challenges','Competency evidence','Learning pathways','Portable records']},
  {slug:'the-college-company',name:'The College Company',stage:'Portfolio development',maturity:'Portfolio development',category:'Collegiate Innovation',question:'What shared infrastructure can connect collegiate competition, creator education and emerging technology?',description:'An umbrella concept for collegiate ventures spanning competition, creator education, emerging technology, intellectual property and student participation.',components:['Education','Ownership','Media','Participation'],focus:'Prioritizing partner pathways across education, media and collegiate participation.',needs:['Universities','Educators','Student organizations','Media partners'],systems:['Creator education','Competition concepts','Collegiate media','Digital property strategy']},
  {slug:'thehomie',name:'TheHomie',stage:'Exploratory concept',maturity:'Portfolio development',category:'Personal Intelligence',question:'How can personal intelligence support better decisions while preserving agency and privacy?',description:'A personal intelligence concept for coordinating decisions across time, habits, health, safety and finances with user-defined guardrails.',components:['Intelligence','Identity','Privacy','Governance'],focus:'Refining the concept, privacy model and bounded initial use cases.',needs:['Privacy experts','Behavioral researchers','Product partners'],systems:['Personal intelligence graph','Context awareness','Decision guardrails','Permission controls']},
  {slug:'artist-intel',name:'Artist Intel',stage:'Exploratory concept',maturity:'Portfolio development',category:'Artist & Rights Intelligence',question:'How can independent artists make better career, audience and rights decisions with accountable intelligence?',description:'Artist Intel is an early-stage concept for unifying career planning, audience insight, opportunity evaluation and rights-aware decision support for artists and their teams.',components:['Intelligence','Rights','Evidence','Creator agency'],focus:'Validating the initial user problem and defining a bounded decision-support workflow.',needs:['Artists','Managers','Rights specialists','Music technology partners'],systems:['Career intelligence','Opportunity screening','Rights and catalog context','Recommendation evidence','Human advisor handoff']},
  {slug:'estate-me',name:'Estate Me',stage:'Concept under review',maturity:'Portfolio development',category:'Digital Legacy & Estate Coordination',question:'How can families organize estate information, memories and decision responsibilities without sacrificing privacy?',description:'Estate Me is an early concept for a secure digital home connecting estate organization, family memory and guided coordination. Product scope and rights remain under review.',components:['Identity','Privacy','Rights','Continuity'],focus:'Clarifying rights, governance, privacy and the smallest responsible use case.',needs:['Estate professionals','Privacy experts','Families','Archival partners'],systems:['Asset and document map','Permission model','Family memory archive','Decision checklist','Professional handoff']},
];

export const advisoryServices=[
  ['01','Emerging Category Architecture','Identify the standards, governance, evidence, rights and participation systems an emerging market needs beyond a product.'],
  ['02','AI & Human–AI Strategy','Determine where AI should support research, decisions, workforce development and operations—with appropriate human oversight.'],
  ['03','Trust, Evidence & Governance','Design measurement, verification, accountability and risk controls that help new systems earn institutional confidence.'],
  ['04','Digital Ownership & Rights','Explore infrastructure for intellectual property, attribution, provenance, licensing, royalties and permissions.'],
  ['05','Venture & Portfolio Architecture','Turn insights and strategic assets into structured opportunities through disciplined validation and stage-based development.'],
  ['06','Partnership & Ecosystem Design','Define how institutions, technology companies, operators, investors and communities can assemble complementary capabilities.'],
];

export const faqs=[
  ['What is an Institution Studio?','An Institution Studio works beyond individual products or companies. It helps design the standards, governance, evidence, ownership systems, economic rails and partnerships that allow an emerging category to function credibly.'],
  ['How is NBG different from a traditional venture studio?','NBG begins with an institutional gap, then determines what combination of research, technology, governance, ventures and partnerships is appropriate. Venture creation is one instrument within the larger architecture.'],
  ['Does every NBG system use blockchain?','No. Blockchain is considered only when it creates a material advantage in verification, provenance, rights, settlement or cross-organizational trust. If a conventional database or payment system solves the problem better, NBG uses it.'],
  ['What stage are the portfolio initiatives in?','Stages vary. The site distinguishes priority architecture, exploratory initiatives, prototype concepts and portfolio development. Each detail page identifies the initiative’s current stage, development focus and partnership needs.'],
  ['What kinds of partners is NBG seeking?','Relevant partners may include technology platforms, universities, employers, health systems, operators, investors, standards organizations, creators and community institutions. Specific needs appear on each portfolio page.'],
  ['How does NBG evaluate new opportunities?','NBG moves from opportunity and institutional gap through architecture, validation, partnership design, evidence, sustainable economics and stewardship. Ideas do not advance on naming or technology alone.'],
];
