import Link from 'next/link';
import { ArrowDownRight,ArrowUpRight,Check,MoveRight } from 'lucide-react';
import { ArchitectureExplorer } from '@/components/architecture-explorer';
import { PartnershipIntake } from '@/components/partnership-intake';
import { researchTracks,ventures } from '@/content/site';
const pillars=['Intelligence','Trust','Ownership','Governance'];
const copy=['Capability to understand, reason, coordinate and act.','Evidence, verification and standards that enable adoption.','Rights, provenance and participation in created value.','Rules, oversight and accountability that create legitimacy.'];
export default function Home(){return <main>
<header className="site-header"><Link className="wordmark" href="/" aria-label="National Brand Group home"><span className="mark" aria-hidden="true">N</span><span>National Brand Group</span></Link><nav aria-label="Primary navigation"><a href="#model">Model</a><a href="#architecture">Architecture</a><a href="#ventures">Ventures</a><a href="#research">Research</a><a href="#about">About</a></nav><a className="header-cta" href="#partner">Build with us <ArrowUpRight size={15}/></a></header>
<section className="hero" aria-labelledby="hero-title"><div className="hero-grid" aria-hidden="true"/><div className="eyebrow"><span/> Institution Studio for the Intelligence Economy</div><h1 id="hero-title">Build the institutions<br/>the future requires.</h1><div className="hero-lower"><p>National Brand Group designs the intelligence, trust, ownership, governance and economic infrastructure that helps emerging categories become functioning markets.</p><div className="hero-actions"><a className="button primary" href="#model">Explore the NBG model <ArrowDownRight size={17}/></a><a className="button ghost" href="#partner">Build with us <ArrowUpRight size={17}/></a></div></div><div className="system-map" aria-hidden="true"><div className="orbit orbit-one"/><div className="orbit orbit-two"/>{pillars.map((p,i)=><span className={`node n${i+1}`} key={p}>{p}</span>)}<span className="core">NBG<small>INSTITUTION<br/>ARCHITECTURE</small></span></div><a className="text-link" href="#ventures">Explore our ventures <ArrowUpRight size={14}/></a></section>
<section className="problem" id="model"><div className="section-index">01 / THE INSTITUTIONAL GAP</div><div><h2>Innovation moves faster<br/>than institutions.</h2><p>New technologies can emerge in months. The systems required to govern them often take decades. Standards. Credentials. Rights. Measurement. Governance. Education. Economic systems. NBG works inside that gap.</p></div><div className="bridge" role="img" aria-label="NBG infrastructure connects emerging technology to a trusted functioning market"><span>Technology</span><div><i/><b>NBG infrastructure</b><i/></div><span>Market</span></div></section>
<section className="formula"><div className="section-index">02 / THE NBG MODEL</div><h2>A reusable architecture<br/>for emerging institutions.</h2><div className="pillars">{pillars.map((p,i)=><article key={p}><span>0{i+1}</span><h3>{p}</h3><p>{copy[i]}</p></article>)}</div><div className="rails"><span>Supported by</span><strong>Economic &amp; Participation Rails</strong><span>Payments · settlement · royalties · commerce · community funding</span></div></section>
<section className="architecture section-dark" id="architecture"><div className="section-head"><div className="section-index">03 / DIGITAL INSTITUTION ARCHITECTURE</div><h2>Seven layers.<br/>Assembled for the problem.</h2><p>Not every institution requires every layer. NBG assembles the architecture appropriate to the problem.</p></div><ArchitectureExplorer/></section>
<section className="ventures" id="ventures"><div className="section-head"><div className="section-index">04 / PORTFOLIO AS PROOF</div><h2>One architecture.<br/>Multiple institutions.</h2><p>These are not unrelated startups. Each explores a distinct institutional problem through shared architecture.</p></div><div className="venture-grid">{ventures.map((v,i)=><article key={v.name} className={i===0?'featured':''}><div><span className="status">{v.stage}</span><span className="venture-no">0{i+1}</span></div><h3>{v.name}</h3><p className="category">{v.category}</p><p className="question">{v.problem}</p><dl><dt>Architecture emphasis</dt><dd>{v.emphasis}</dd><dt>Primary partnership needs</dt><dd>{v.need}</dd></dl>{i===0&&<div className="proof-flow" aria-label="AGONiQ prototype architecture: challenge to human and AI performance, evidence, scoring, verification, credential, and portable reputation">Challenge <MoveRight/> Human + AI Performance <MoveRight/> Evidence <MoveRight/> Credential</div>}</article>)}</div></section>
<section className="ownership"><div className="section-index">05 / OWNERSHIP &amp; SETTLEMENT</div><div className="split-copy"><div><h2>The Intelligence Economy needs an ownership layer.</h2><p>Infrastructure for a world where intelligence, rights and economic participation increasingly move across digital systems.</p></div><div className="questions">{['Who created this?','Who contributed?','Who owns it?','Who may use it?','How should value be distributed?'].map(x=><p key={x}><Check size={14}/>{x}</p>)}</div></div><div className="distinction"><div><span>Not our focus</span><strong>Speculation</strong><p>Token prices, trading interfaces or ideology.</p></div><MoveRight/><div><span>Our focus</span><strong>Infrastructure</strong><p>Identity, attestations, rights, licensing, royalties and appropriate settlement.</p></div></div><blockquote>“If a conventional database or payment system solves the problem better, use it.”</blockquote><p className="chain-note">Blockchain is one optional, chain-agnostic infrastructure choice—evaluated only where it creates a material advantage in verification, provenance, rights, settlement or cross-organizational trust.</p></section>
<section className="lab" id="research"><div className="section-head"><span className="status">Research + Prototyping</span><div className="section-index">06 / NBG DIGITAL ASSET INFRASTRUCTURE LAB</div><h2>Questions before products.</h2><p>A shared research capability supporting existing NBG ventures—not a standalone venture.</p></div><div className="research-list">{researchTracks.map(([n,title,context,q])=><article key={n}><span>{n}</span><div><h3>{title}</h3><small>{context}</small></div><p>{q}</p></article>)}</div></section>
<section className="research-shell"><div><div className="section-index">07 / NBG INTELLIGENCE</div><h2>We study markets<br/>before we build them.</h2></div><div className="topic-cloud">{['Human–AI performance','AI workforce readiness','Digital ownership','Future credentials','Digital identity','Creator economics','AI-native institutions','Patient-centered AI','Esports & competition','Cabo Verde opportunity'].map(x=><span key={x}>{x}</span>)}</div><p className="prototype-note">Research publication system in development. Themes indicate current areas of inquiry, not completed studies or validated market claims.</p></section>
<section className="about" id="about"><div className="section-index">08 / ABOUT NBG</div><div><h2>Institution building across culture, technology and markets.</h2><p>National Brand Group operates at the intersection of research, standards, technology, venture creation and strategic partnership. Founder Kevin Mitchell brings a cross-disciplinary perspective spanning culture, media, technology, education, esports, AI and venture development.</p><p className="founder-role">Kevin Mitchell <span>Founder · Venture Architect · Institution Builder</span></p></div></section>
<section className="partner" id="partner"><div className="partner-intro"><div className="section-index">09 / PARTNERSHIP ENGINE</div><h2>What institution<br/>does your market need?</h2><p>NBG collaborates with technology companies, universities, operators, investors and institutions building the infrastructure of emerging markets.</p><p className="ecosystem-note">We don’t need to build every layer ourselves. The next generation of institutions will be assembled through ecosystems.</p></div><PartnershipIntake/></section>
<footer><div className="wordmark"><span className="mark">N</span><span>National Brand Group</span></div><p>Institution Studio for the Intelligence Economy</p><a href="mailto:hello@nationalbrandgroup.com">Contact NBG <ArrowUpRight size={14}/></a><small>© {new Date().getFullYear()} National Brand Group. Exploratory initiatives and prototype architectures are labeled throughout.</small></footer>
</main>}
